version: '3.8'
services:
  app:
    build: .
    ports:
      - "${PORT}:3000"  # Expose the port specified in .env, mapped to port 3000 in the container
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules  # Persist node_modules volume

  db:
    image: mysql:8.0  # Using MySQL version 8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql  # Persist MySQL data
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 20s  # Expose MySQL on port 3306

volumes:
  db-data:  # Defines the volume for persisting database data
